# Generated by Django 5.0.6 on 2024-06-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='BlogImage/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
