# Generated by Django 5.0.6 on 2024-06-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='BlogImage/default_error.png', upload_to='BlogImage/%Y/%m/%d/'),
        ),
    ]
